### PR TITLE
Pinning script

### PR DESCRIPTION
**Pull request by giorgiosironi**
This script will be useful for the bot to specify a fixed version of elife-poa-xml-generation. It will be called by elife-bot-formula specifying the path of a file contained in the elife-bot repository (similar to Lax's equivalent for bot-lax-adaptor, https://github.com/elifesciences/lax/blob/develop/bot-lax-adaptor.sha1).

This way, the bot carries together a fixed version of
elife-poa-xml-generation, that gets tested in ci and end2end along with
it.

### CODE REVIEW

**Comment by giorgiosironi** [comment]
You mean the version of `elifetools` use by /opt/elife-bot/ vs the version of `elifetools` use by /opt/elife-poa-xml-generation? That coud probably be harmonized by pinning a similar sha1 (or version number) later.

**Comment by gnott** [comment]
I'm not sure if this is out-of-date now? I think in the elife-bot-formula we deploy the master branch of this project. 

Plans are I want to refactor this library to be split into three new libraries - Crossref is done, Pubmed is part done, then the PoA generation into a third library. I don't think we'll need more granularity on this particular project.

Any additional thoughts @giorgiosironi ?

**Comment by giorgiosironi** [comment]
This was forgotten and left open, but should still work until the library is removed (if it is) in favor of the multiple, smaller libraries.

If the new libraries are installed through pip, they won't need these tricky scripts.

**Comment by gnott** [comment]
Thanks, I'll merge and we'll give it a go!

**Comment by giorgiosironi** [comment]
Merging also https://github.com/elifesciences/elife-bot-formula/pull/5 which was related.

**Pull request merged**
